### ISSUE TITLE
[RFE] Making sets of options optional 

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/typedconfig#17]
Sometimes there are entire branches of options that are only relevant in specific models, leading to no purpose for their inclusion in a model's configuration file. Yet, because they are in the ruleset, the validation fails due to an expectation that those options will be there. E.g. 
```
run
  __init__() missing 2 required positional arguments: 'operate_options' and 'postprocess_options' (type=type_error)
```

Where the ruleset includes:

```yaml
run:
  backend:
    type: Literal
    opts: [pyomo, gurobi]
    doc: Points to the solver interface that will be used on running the model
  operate_options:
    horizon:
      type: Text  # pandas.Timedelta
    window:
      validator: range_check  # window >= horizon, i.e. the same as [min, max]
      type: Text  # pandas.Timedelta
  postprocess_options:
    zero_threshold:
      type: PositiveFloat
      default: !!float 1e-10
```

So, a user has defined `backend`, but doesn't want to define anything under `operate_options` and `postprocess_options`. Basically, it should be possible to ignore the non existence of certain configuration options on validating.
